/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as KnowledgesIndexImport } from './routes/knowledges/index'
import { Route as FinancesIndexImport } from './routes/finances/index'
import { Route as AboutusIndexImport } from './routes/about_us/index'
import { Route as KnowledgesProgrammingIndexImport } from './routes/knowledges/programming/index'
import { Route as KnowledgesEnglishIndexImport } from './routes/knowledges/english/index'
import { Route as KnowledgesEnglishCreateImport } from './routes/knowledges/english/create'
import { Route as KnowledgesEnglishUnitImport } from './routes/knowledges/english/$unit'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const KnowledgesIndexRoute = KnowledgesIndexImport.update({
  id: '/knowledges/',
  path: '/knowledges/',
  getParentRoute: () => rootRoute,
} as any)

const FinancesIndexRoute = FinancesIndexImport.update({
  id: '/finances/',
  path: '/finances/',
  getParentRoute: () => rootRoute,
} as any)

const AboutusIndexRoute = AboutusIndexImport.update({
  id: '/about_us/',
  path: '/about_us/',
  getParentRoute: () => rootRoute,
} as any)

const KnowledgesProgrammingIndexRoute = KnowledgesProgrammingIndexImport.update(
  {
    id: '/knowledges/programming/',
    path: '/knowledges/programming/',
    getParentRoute: () => rootRoute,
  } as any,
)

const KnowledgesEnglishIndexRoute = KnowledgesEnglishIndexImport.update({
  id: '/knowledges/english/',
  path: '/knowledges/english/',
  getParentRoute: () => rootRoute,
} as any)

const KnowledgesEnglishCreateRoute = KnowledgesEnglishCreateImport.update({
  id: '/knowledges/english/create',
  path: '/knowledges/english/create',
  getParentRoute: () => rootRoute,
} as any)

const KnowledgesEnglishUnitRoute = KnowledgesEnglishUnitImport.update({
  id: '/knowledges/english/$unit',
  path: '/knowledges/english/$unit',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about_us/': {
      id: '/about_us/'
      path: '/about_us'
      fullPath: '/about_us'
      preLoaderRoute: typeof AboutusIndexImport
      parentRoute: typeof rootRoute
    }
    '/finances/': {
      id: '/finances/'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof FinancesIndexImport
      parentRoute: typeof rootRoute
    }
    '/knowledges/': {
      id: '/knowledges/'
      path: '/knowledges'
      fullPath: '/knowledges'
      preLoaderRoute: typeof KnowledgesIndexImport
      parentRoute: typeof rootRoute
    }
    '/knowledges/english/$unit': {
      id: '/knowledges/english/$unit'
      path: '/knowledges/english/$unit'
      fullPath: '/knowledges/english/$unit'
      preLoaderRoute: typeof KnowledgesEnglishUnitImport
      parentRoute: typeof rootRoute
    }
    '/knowledges/english/create': {
      id: '/knowledges/english/create'
      path: '/knowledges/english/create'
      fullPath: '/knowledges/english/create'
      preLoaderRoute: typeof KnowledgesEnglishCreateImport
      parentRoute: typeof rootRoute
    }
    '/knowledges/english/': {
      id: '/knowledges/english/'
      path: '/knowledges/english'
      fullPath: '/knowledges/english'
      preLoaderRoute: typeof KnowledgesEnglishIndexImport
      parentRoute: typeof rootRoute
    }
    '/knowledges/programming/': {
      id: '/knowledges/programming/'
      path: '/knowledges/programming'
      fullPath: '/knowledges/programming'
      preLoaderRoute: typeof KnowledgesProgrammingIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about_us': typeof AboutusIndexRoute
  '/finances': typeof FinancesIndexRoute
  '/knowledges': typeof KnowledgesIndexRoute
  '/knowledges/english/$unit': typeof KnowledgesEnglishUnitRoute
  '/knowledges/english/create': typeof KnowledgesEnglishCreateRoute
  '/knowledges/english': typeof KnowledgesEnglishIndexRoute
  '/knowledges/programming': typeof KnowledgesProgrammingIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about_us': typeof AboutusIndexRoute
  '/finances': typeof FinancesIndexRoute
  '/knowledges': typeof KnowledgesIndexRoute
  '/knowledges/english/$unit': typeof KnowledgesEnglishUnitRoute
  '/knowledges/english/create': typeof KnowledgesEnglishCreateRoute
  '/knowledges/english': typeof KnowledgesEnglishIndexRoute
  '/knowledges/programming': typeof KnowledgesProgrammingIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about_us/': typeof AboutusIndexRoute
  '/finances/': typeof FinancesIndexRoute
  '/knowledges/': typeof KnowledgesIndexRoute
  '/knowledges/english/$unit': typeof KnowledgesEnglishUnitRoute
  '/knowledges/english/create': typeof KnowledgesEnglishCreateRoute
  '/knowledges/english/': typeof KnowledgesEnglishIndexRoute
  '/knowledges/programming/': typeof KnowledgesProgrammingIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about_us'
    | '/finances'
    | '/knowledges'
    | '/knowledges/english/$unit'
    | '/knowledges/english/create'
    | '/knowledges/english'
    | '/knowledges/programming'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about_us'
    | '/finances'
    | '/knowledges'
    | '/knowledges/english/$unit'
    | '/knowledges/english/create'
    | '/knowledges/english'
    | '/knowledges/programming'
  id:
    | '__root__'
    | '/'
    | '/about_us/'
    | '/finances/'
    | '/knowledges/'
    | '/knowledges/english/$unit'
    | '/knowledges/english/create'
    | '/knowledges/english/'
    | '/knowledges/programming/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutusIndexRoute: typeof AboutusIndexRoute
  FinancesIndexRoute: typeof FinancesIndexRoute
  KnowledgesIndexRoute: typeof KnowledgesIndexRoute
  KnowledgesEnglishUnitRoute: typeof KnowledgesEnglishUnitRoute
  KnowledgesEnglishCreateRoute: typeof KnowledgesEnglishCreateRoute
  KnowledgesEnglishIndexRoute: typeof KnowledgesEnglishIndexRoute
  KnowledgesProgrammingIndexRoute: typeof KnowledgesProgrammingIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutusIndexRoute: AboutusIndexRoute,
  FinancesIndexRoute: FinancesIndexRoute,
  KnowledgesIndexRoute: KnowledgesIndexRoute,
  KnowledgesEnglishUnitRoute: KnowledgesEnglishUnitRoute,
  KnowledgesEnglishCreateRoute: KnowledgesEnglishCreateRoute,
  KnowledgesEnglishIndexRoute: KnowledgesEnglishIndexRoute,
  KnowledgesProgrammingIndexRoute: KnowledgesProgrammingIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about_us/",
        "/finances/",
        "/knowledges/",
        "/knowledges/english/$unit",
        "/knowledges/english/create",
        "/knowledges/english/",
        "/knowledges/programming/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about_us/": {
      "filePath": "about_us/index.tsx"
    },
    "/finances/": {
      "filePath": "finances/index.tsx"
    },
    "/knowledges/": {
      "filePath": "knowledges/index.tsx"
    },
    "/knowledges/english/$unit": {
      "filePath": "knowledges/english/$unit.tsx"
    },
    "/knowledges/english/create": {
      "filePath": "knowledges/english/create.tsx"
    },
    "/knowledges/english/": {
      "filePath": "knowledges/english/index.tsx"
    },
    "/knowledges/programming/": {
      "filePath": "knowledges/programming/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
