/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as TravelsIndexImport } from './routes/travels/index'
import { Route as TestIndexImport } from './routes/test/index'
import { Route as NotesIndexImport } from './routes/notes/index'
import { Route as KnowledgesIndexImport } from './routes/knowledges/index'
import { Route as FinancesIndexImport } from './routes/finances/index'
import { Route as ExpensesIndexImport } from './routes/expenses/index'
import { Route as AboutusIndexImport } from './routes/about_us/index'
import { Route as TravelsPathlessLayoutRouteImport } from './routes/travels/_pathlessLayout/route'
import { Route as NotesPathlessLayoutRouteImport } from './routes/notes/_pathlessLayout/route'
import { Route as KnowledgesProgrammingIndexImport } from './routes/knowledges/programming/index'
import { Route as KnowledgesEnglishIndexImport } from './routes/knowledges/english/index'
import { Route as KnowledgesProgrammingCreateImport } from './routes/knowledges/programming/create'
import { Route as KnowledgesEnglishVocabulariesImport } from './routes/knowledges/english/vocabularies'
import { Route as KnowledgesEnglishCreateImport } from './routes/knowledges/english/create'
import { Route as TravelsPathlessLayoutFoodsIndexImport } from './routes/travels/_pathlessLayout/foods/index'
import { Route as TravelsPathlessLayoutCoffeesIndexImport } from './routes/travels/_pathlessLayout/coffees/index'
import { Route as NotesPathlessLayoutBooksIndexImport } from './routes/notes/_pathlessLayout/books/index'
import { Route as KnowledgesProgrammingUnitIndexImport } from './routes/knowledges/programming/$unit/index'
import { Route as KnowledgesEnglishUnitIndexImport } from './routes/knowledges/english/$unit/index'
import { Route as TravelsPathlessLayoutFoodsTestImport } from './routes/travels/_pathlessLayout/foods/test'
import { Route as NotesPathlessLayoutBooksCreateImport } from './routes/notes/_pathlessLayout/books/create'
import { Route as NotesPathlessLayoutBooksIdImport } from './routes/notes/_pathlessLayout/books/$id'
import { Route as KnowledgesEnglishUnitEditImport } from './routes/knowledges/english/$unit/edit'

// Create Virtual Routes

const TravelsImport = createFileRoute('/travels')()
const NotesImport = createFileRoute('/notes')()

// Create/Update Routes

const TravelsRoute = TravelsImport.update({
  id: '/travels',
  path: '/travels',
  getParentRoute: () => rootRoute,
} as any)

const NotesRoute = NotesImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TravelsIndexRoute = TravelsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TravelsRoute,
} as any)

const TestIndexRoute = TestIndexImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => rootRoute,
} as any)

const NotesIndexRoute = NotesIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NotesRoute,
} as any)

const KnowledgesIndexRoute = KnowledgesIndexImport.update({
  id: '/knowledges/',
  path: '/knowledges/',
  getParentRoute: () => rootRoute,
} as any)

const FinancesIndexRoute = FinancesIndexImport.update({
  id: '/finances/',
  path: '/finances/',
  getParentRoute: () => rootRoute,
} as any)

const ExpensesIndexRoute = ExpensesIndexImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => rootRoute,
} as any)

const AboutusIndexRoute = AboutusIndexImport.update({
  id: '/about_us/',
  path: '/about_us/',
  getParentRoute: () => rootRoute,
} as any)

const TravelsPathlessLayoutRouteRoute = TravelsPathlessLayoutRouteImport.update(
  {
    id: '/_pathlessLayout',
    getParentRoute: () => TravelsRoute,
  } as any,
)

const NotesPathlessLayoutRouteRoute = NotesPathlessLayoutRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => NotesRoute,
} as any)

const KnowledgesProgrammingIndexRoute = KnowledgesProgrammingIndexImport.update(
  {
    id: '/knowledges/programming/',
    path: '/knowledges/programming/',
    getParentRoute: () => rootRoute,
  } as any,
)

const KnowledgesEnglishIndexRoute = KnowledgesEnglishIndexImport.update({
  id: '/knowledges/english/',
  path: '/knowledges/english/',
  getParentRoute: () => rootRoute,
} as any)

const KnowledgesProgrammingCreateRoute =
  KnowledgesProgrammingCreateImport.update({
    id: '/knowledges/programming/create',
    path: '/knowledges/programming/create',
    getParentRoute: () => rootRoute,
  } as any)

const KnowledgesEnglishVocabulariesRoute =
  KnowledgesEnglishVocabulariesImport.update({
    id: '/knowledges/english/vocabularies',
    path: '/knowledges/english/vocabularies',
    getParentRoute: () => rootRoute,
  } as any)

const KnowledgesEnglishCreateRoute = KnowledgesEnglishCreateImport.update({
  id: '/knowledges/english/create',
  path: '/knowledges/english/create',
  getParentRoute: () => rootRoute,
} as any)

const TravelsPathlessLayoutFoodsIndexRoute =
  TravelsPathlessLayoutFoodsIndexImport.update({
    id: '/foods/',
    path: '/foods/',
    getParentRoute: () => TravelsPathlessLayoutRouteRoute,
  } as any)

const TravelsPathlessLayoutCoffeesIndexRoute =
  TravelsPathlessLayoutCoffeesIndexImport.update({
    id: '/coffees/',
    path: '/coffees/',
    getParentRoute: () => TravelsPathlessLayoutRouteRoute,
  } as any)

const NotesPathlessLayoutBooksIndexRoute =
  NotesPathlessLayoutBooksIndexImport.update({
    id: '/books/',
    path: '/books/',
    getParentRoute: () => NotesPathlessLayoutRouteRoute,
  } as any)

const KnowledgesProgrammingUnitIndexRoute =
  KnowledgesProgrammingUnitIndexImport.update({
    id: '/knowledges/programming/$unit/',
    path: '/knowledges/programming/$unit/',
    getParentRoute: () => rootRoute,
  } as any)

const KnowledgesEnglishUnitIndexRoute = KnowledgesEnglishUnitIndexImport.update(
  {
    id: '/knowledges/english/$unit/',
    path: '/knowledges/english/$unit/',
    getParentRoute: () => rootRoute,
  } as any,
)

const TravelsPathlessLayoutFoodsTestRoute =
  TravelsPathlessLayoutFoodsTestImport.update({
    id: '/foods/test',
    path: '/foods/test',
    getParentRoute: () => TravelsPathlessLayoutRouteRoute,
  } as any)

const NotesPathlessLayoutBooksCreateRoute =
  NotesPathlessLayoutBooksCreateImport.update({
    id: '/books/create',
    path: '/books/create',
    getParentRoute: () => NotesPathlessLayoutRouteRoute,
  } as any)

const NotesPathlessLayoutBooksIdRoute = NotesPathlessLayoutBooksIdImport.update(
  {
    id: '/books/$id',
    path: '/books/$id',
    getParentRoute: () => NotesPathlessLayoutRouteRoute,
  } as any,
)

const KnowledgesEnglishUnitEditRoute = KnowledgesEnglishUnitEditImport.update({
  id: '/knowledges/english/$unit/edit',
  path: '/knowledges/english/$unit/edit',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesImport
      parentRoute: typeof rootRoute
    }
    '/notes/_pathlessLayout': {
      id: '/notes/_pathlessLayout'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesPathlessLayoutRouteImport
      parentRoute: typeof NotesRoute
    }
    '/travels': {
      id: '/travels'
      path: '/travels'
      fullPath: '/travels'
      preLoaderRoute: typeof TravelsImport
      parentRoute: typeof rootRoute
    }
    '/travels/_pathlessLayout': {
      id: '/travels/_pathlessLayout'
      path: '/travels'
      fullPath: '/travels'
      preLoaderRoute: typeof TravelsPathlessLayoutRouteImport
      parentRoute: typeof TravelsRoute
    }
    '/about_us/': {
      id: '/about_us/'
      path: '/about_us'
      fullPath: '/about_us'
      preLoaderRoute: typeof AboutusIndexImport
      parentRoute: typeof rootRoute
    }
    '/expenses/': {
      id: '/expenses/'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesIndexImport
      parentRoute: typeof rootRoute
    }
    '/finances/': {
      id: '/finances/'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof FinancesIndexImport
      parentRoute: typeof rootRoute
    }
    '/knowledges/': {
      id: '/knowledges/'
      path: '/knowledges'
      fullPath: '/knowledges'
      preLoaderRoute: typeof KnowledgesIndexImport
      parentRoute: typeof rootRoute
    }
    '/notes/': {
      id: '/notes/'
      path: '/'
      fullPath: '/notes/'
      preLoaderRoute: typeof NotesIndexImport
      parentRoute: typeof NotesImport
    }
    '/test/': {
      id: '/test/'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestIndexImport
      parentRoute: typeof rootRoute
    }
    '/travels/': {
      id: '/travels/'
      path: '/'
      fullPath: '/travels/'
      preLoaderRoute: typeof TravelsIndexImport
      parentRoute: typeof TravelsImport
    }
    '/knowledges/english/create': {
      id: '/knowledges/english/create'
      path: '/knowledges/english/create'
      fullPath: '/knowledges/english/create'
      preLoaderRoute: typeof KnowledgesEnglishCreateImport
      parentRoute: typeof rootRoute
    }
    '/knowledges/english/vocabularies': {
      id: '/knowledges/english/vocabularies'
      path: '/knowledges/english/vocabularies'
      fullPath: '/knowledges/english/vocabularies'
      preLoaderRoute: typeof KnowledgesEnglishVocabulariesImport
      parentRoute: typeof rootRoute
    }
    '/knowledges/programming/create': {
      id: '/knowledges/programming/create'
      path: '/knowledges/programming/create'
      fullPath: '/knowledges/programming/create'
      preLoaderRoute: typeof KnowledgesProgrammingCreateImport
      parentRoute: typeof rootRoute
    }
    '/knowledges/english/': {
      id: '/knowledges/english/'
      path: '/knowledges/english'
      fullPath: '/knowledges/english'
      preLoaderRoute: typeof KnowledgesEnglishIndexImport
      parentRoute: typeof rootRoute
    }
    '/knowledges/programming/': {
      id: '/knowledges/programming/'
      path: '/knowledges/programming'
      fullPath: '/knowledges/programming'
      preLoaderRoute: typeof KnowledgesProgrammingIndexImport
      parentRoute: typeof rootRoute
    }
    '/knowledges/english/$unit/edit': {
      id: '/knowledges/english/$unit/edit'
      path: '/knowledges/english/$unit/edit'
      fullPath: '/knowledges/english/$unit/edit'
      preLoaderRoute: typeof KnowledgesEnglishUnitEditImport
      parentRoute: typeof rootRoute
    }
    '/notes/_pathlessLayout/books/$id': {
      id: '/notes/_pathlessLayout/books/$id'
      path: '/books/$id'
      fullPath: '/notes/books/$id'
      preLoaderRoute: typeof NotesPathlessLayoutBooksIdImport
      parentRoute: typeof NotesPathlessLayoutRouteImport
    }
    '/notes/_pathlessLayout/books/create': {
      id: '/notes/_pathlessLayout/books/create'
      path: '/books/create'
      fullPath: '/notes/books/create'
      preLoaderRoute: typeof NotesPathlessLayoutBooksCreateImport
      parentRoute: typeof NotesPathlessLayoutRouteImport
    }
    '/travels/_pathlessLayout/foods/test': {
      id: '/travels/_pathlessLayout/foods/test'
      path: '/foods/test'
      fullPath: '/travels/foods/test'
      preLoaderRoute: typeof TravelsPathlessLayoutFoodsTestImport
      parentRoute: typeof TravelsPathlessLayoutRouteImport
    }
    '/knowledges/english/$unit/': {
      id: '/knowledges/english/$unit/'
      path: '/knowledges/english/$unit'
      fullPath: '/knowledges/english/$unit'
      preLoaderRoute: typeof KnowledgesEnglishUnitIndexImport
      parentRoute: typeof rootRoute
    }
    '/knowledges/programming/$unit/': {
      id: '/knowledges/programming/$unit/'
      path: '/knowledges/programming/$unit'
      fullPath: '/knowledges/programming/$unit'
      preLoaderRoute: typeof KnowledgesProgrammingUnitIndexImport
      parentRoute: typeof rootRoute
    }
    '/notes/_pathlessLayout/books/': {
      id: '/notes/_pathlessLayout/books/'
      path: '/books'
      fullPath: '/notes/books'
      preLoaderRoute: typeof NotesPathlessLayoutBooksIndexImport
      parentRoute: typeof NotesPathlessLayoutRouteImport
    }
    '/travels/_pathlessLayout/coffees/': {
      id: '/travels/_pathlessLayout/coffees/'
      path: '/coffees'
      fullPath: '/travels/coffees'
      preLoaderRoute: typeof TravelsPathlessLayoutCoffeesIndexImport
      parentRoute: typeof TravelsPathlessLayoutRouteImport
    }
    '/travels/_pathlessLayout/foods/': {
      id: '/travels/_pathlessLayout/foods/'
      path: '/foods'
      fullPath: '/travels/foods'
      preLoaderRoute: typeof TravelsPathlessLayoutFoodsIndexImport
      parentRoute: typeof TravelsPathlessLayoutRouteImport
    }
  }
}

// Create and export the route tree

interface NotesPathlessLayoutRouteRouteChildren {
  NotesPathlessLayoutBooksIdRoute: typeof NotesPathlessLayoutBooksIdRoute
  NotesPathlessLayoutBooksCreateRoute: typeof NotesPathlessLayoutBooksCreateRoute
  NotesPathlessLayoutBooksIndexRoute: typeof NotesPathlessLayoutBooksIndexRoute
}

const NotesPathlessLayoutRouteRouteChildren: NotesPathlessLayoutRouteRouteChildren =
  {
    NotesPathlessLayoutBooksIdRoute: NotesPathlessLayoutBooksIdRoute,
    NotesPathlessLayoutBooksCreateRoute: NotesPathlessLayoutBooksCreateRoute,
    NotesPathlessLayoutBooksIndexRoute: NotesPathlessLayoutBooksIndexRoute,
  }

const NotesPathlessLayoutRouteRouteWithChildren =
  NotesPathlessLayoutRouteRoute._addFileChildren(
    NotesPathlessLayoutRouteRouteChildren,
  )

interface NotesRouteChildren {
  NotesPathlessLayoutRouteRoute: typeof NotesPathlessLayoutRouteRouteWithChildren
  NotesIndexRoute: typeof NotesIndexRoute
}

const NotesRouteChildren: NotesRouteChildren = {
  NotesPathlessLayoutRouteRoute: NotesPathlessLayoutRouteRouteWithChildren,
  NotesIndexRoute: NotesIndexRoute,
}

const NotesRouteWithChildren = NotesRoute._addFileChildren(NotesRouteChildren)

interface TravelsPathlessLayoutRouteRouteChildren {
  TravelsPathlessLayoutFoodsTestRoute: typeof TravelsPathlessLayoutFoodsTestRoute
  TravelsPathlessLayoutCoffeesIndexRoute: typeof TravelsPathlessLayoutCoffeesIndexRoute
  TravelsPathlessLayoutFoodsIndexRoute: typeof TravelsPathlessLayoutFoodsIndexRoute
}

const TravelsPathlessLayoutRouteRouteChildren: TravelsPathlessLayoutRouteRouteChildren =
  {
    TravelsPathlessLayoutFoodsTestRoute: TravelsPathlessLayoutFoodsTestRoute,
    TravelsPathlessLayoutCoffeesIndexRoute:
      TravelsPathlessLayoutCoffeesIndexRoute,
    TravelsPathlessLayoutFoodsIndexRoute: TravelsPathlessLayoutFoodsIndexRoute,
  }

const TravelsPathlessLayoutRouteRouteWithChildren =
  TravelsPathlessLayoutRouteRoute._addFileChildren(
    TravelsPathlessLayoutRouteRouteChildren,
  )

interface TravelsRouteChildren {
  TravelsPathlessLayoutRouteRoute: typeof TravelsPathlessLayoutRouteRouteWithChildren
  TravelsIndexRoute: typeof TravelsIndexRoute
}

const TravelsRouteChildren: TravelsRouteChildren = {
  TravelsPathlessLayoutRouteRoute: TravelsPathlessLayoutRouteRouteWithChildren,
  TravelsIndexRoute: TravelsIndexRoute,
}

const TravelsRouteWithChildren =
  TravelsRoute._addFileChildren(TravelsRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notes': typeof NotesPathlessLayoutRouteRouteWithChildren
  '/travels': typeof TravelsPathlessLayoutRouteRouteWithChildren
  '/about_us': typeof AboutusIndexRoute
  '/expenses': typeof ExpensesIndexRoute
  '/finances': typeof FinancesIndexRoute
  '/knowledges': typeof KnowledgesIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/test': typeof TestIndexRoute
  '/travels/': typeof TravelsIndexRoute
  '/knowledges/english/create': typeof KnowledgesEnglishCreateRoute
  '/knowledges/english/vocabularies': typeof KnowledgesEnglishVocabulariesRoute
  '/knowledges/programming/create': typeof KnowledgesProgrammingCreateRoute
  '/knowledges/english': typeof KnowledgesEnglishIndexRoute
  '/knowledges/programming': typeof KnowledgesProgrammingIndexRoute
  '/knowledges/english/$unit/edit': typeof KnowledgesEnglishUnitEditRoute
  '/notes/books/$id': typeof NotesPathlessLayoutBooksIdRoute
  '/notes/books/create': typeof NotesPathlessLayoutBooksCreateRoute
  '/travels/foods/test': typeof TravelsPathlessLayoutFoodsTestRoute
  '/knowledges/english/$unit': typeof KnowledgesEnglishUnitIndexRoute
  '/knowledges/programming/$unit': typeof KnowledgesProgrammingUnitIndexRoute
  '/notes/books': typeof NotesPathlessLayoutBooksIndexRoute
  '/travels/coffees': typeof TravelsPathlessLayoutCoffeesIndexRoute
  '/travels/foods': typeof TravelsPathlessLayoutFoodsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notes': typeof NotesIndexRoute
  '/travels': typeof TravelsIndexRoute
  '/about_us': typeof AboutusIndexRoute
  '/expenses': typeof ExpensesIndexRoute
  '/finances': typeof FinancesIndexRoute
  '/knowledges': typeof KnowledgesIndexRoute
  '/test': typeof TestIndexRoute
  '/knowledges/english/create': typeof KnowledgesEnglishCreateRoute
  '/knowledges/english/vocabularies': typeof KnowledgesEnglishVocabulariesRoute
  '/knowledges/programming/create': typeof KnowledgesProgrammingCreateRoute
  '/knowledges/english': typeof KnowledgesEnglishIndexRoute
  '/knowledges/programming': typeof KnowledgesProgrammingIndexRoute
  '/knowledges/english/$unit/edit': typeof KnowledgesEnglishUnitEditRoute
  '/notes/books/$id': typeof NotesPathlessLayoutBooksIdRoute
  '/notes/books/create': typeof NotesPathlessLayoutBooksCreateRoute
  '/travels/foods/test': typeof TravelsPathlessLayoutFoodsTestRoute
  '/knowledges/english/$unit': typeof KnowledgesEnglishUnitIndexRoute
  '/knowledges/programming/$unit': typeof KnowledgesProgrammingUnitIndexRoute
  '/notes/books': typeof NotesPathlessLayoutBooksIndexRoute
  '/travels/coffees': typeof TravelsPathlessLayoutCoffeesIndexRoute
  '/travels/foods': typeof TravelsPathlessLayoutFoodsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/notes': typeof NotesRouteWithChildren
  '/notes/_pathlessLayout': typeof NotesPathlessLayoutRouteRouteWithChildren
  '/travels': typeof TravelsRouteWithChildren
  '/travels/_pathlessLayout': typeof TravelsPathlessLayoutRouteRouteWithChildren
  '/about_us/': typeof AboutusIndexRoute
  '/expenses/': typeof ExpensesIndexRoute
  '/finances/': typeof FinancesIndexRoute
  '/knowledges/': typeof KnowledgesIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/test/': typeof TestIndexRoute
  '/travels/': typeof TravelsIndexRoute
  '/knowledges/english/create': typeof KnowledgesEnglishCreateRoute
  '/knowledges/english/vocabularies': typeof KnowledgesEnglishVocabulariesRoute
  '/knowledges/programming/create': typeof KnowledgesProgrammingCreateRoute
  '/knowledges/english/': typeof KnowledgesEnglishIndexRoute
  '/knowledges/programming/': typeof KnowledgesProgrammingIndexRoute
  '/knowledges/english/$unit/edit': typeof KnowledgesEnglishUnitEditRoute
  '/notes/_pathlessLayout/books/$id': typeof NotesPathlessLayoutBooksIdRoute
  '/notes/_pathlessLayout/books/create': typeof NotesPathlessLayoutBooksCreateRoute
  '/travels/_pathlessLayout/foods/test': typeof TravelsPathlessLayoutFoodsTestRoute
  '/knowledges/english/$unit/': typeof KnowledgesEnglishUnitIndexRoute
  '/knowledges/programming/$unit/': typeof KnowledgesProgrammingUnitIndexRoute
  '/notes/_pathlessLayout/books/': typeof NotesPathlessLayoutBooksIndexRoute
  '/travels/_pathlessLayout/coffees/': typeof TravelsPathlessLayoutCoffeesIndexRoute
  '/travels/_pathlessLayout/foods/': typeof TravelsPathlessLayoutFoodsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/notes'
    | '/travels'
    | '/about_us'
    | '/expenses'
    | '/finances'
    | '/knowledges'
    | '/notes/'
    | '/test'
    | '/travels/'
    | '/knowledges/english/create'
    | '/knowledges/english/vocabularies'
    | '/knowledges/programming/create'
    | '/knowledges/english'
    | '/knowledges/programming'
    | '/knowledges/english/$unit/edit'
    | '/notes/books/$id'
    | '/notes/books/create'
    | '/travels/foods/test'
    | '/knowledges/english/$unit'
    | '/knowledges/programming/$unit'
    | '/notes/books'
    | '/travels/coffees'
    | '/travels/foods'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/notes'
    | '/travels'
    | '/about_us'
    | '/expenses'
    | '/finances'
    | '/knowledges'
    | '/test'
    | '/knowledges/english/create'
    | '/knowledges/english/vocabularies'
    | '/knowledges/programming/create'
    | '/knowledges/english'
    | '/knowledges/programming'
    | '/knowledges/english/$unit/edit'
    | '/notes/books/$id'
    | '/notes/books/create'
    | '/travels/foods/test'
    | '/knowledges/english/$unit'
    | '/knowledges/programming/$unit'
    | '/notes/books'
    | '/travels/coffees'
    | '/travels/foods'
  id:
    | '__root__'
    | '/'
    | '/notes'
    | '/notes/_pathlessLayout'
    | '/travels'
    | '/travels/_pathlessLayout'
    | '/about_us/'
    | '/expenses/'
    | '/finances/'
    | '/knowledges/'
    | '/notes/'
    | '/test/'
    | '/travels/'
    | '/knowledges/english/create'
    | '/knowledges/english/vocabularies'
    | '/knowledges/programming/create'
    | '/knowledges/english/'
    | '/knowledges/programming/'
    | '/knowledges/english/$unit/edit'
    | '/notes/_pathlessLayout/books/$id'
    | '/notes/_pathlessLayout/books/create'
    | '/travels/_pathlessLayout/foods/test'
    | '/knowledges/english/$unit/'
    | '/knowledges/programming/$unit/'
    | '/notes/_pathlessLayout/books/'
    | '/travels/_pathlessLayout/coffees/'
    | '/travels/_pathlessLayout/foods/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotesRoute: typeof NotesRouteWithChildren
  TravelsRoute: typeof TravelsRouteWithChildren
  AboutusIndexRoute: typeof AboutusIndexRoute
  ExpensesIndexRoute: typeof ExpensesIndexRoute
  FinancesIndexRoute: typeof FinancesIndexRoute
  KnowledgesIndexRoute: typeof KnowledgesIndexRoute
  TestIndexRoute: typeof TestIndexRoute
  KnowledgesEnglishCreateRoute: typeof KnowledgesEnglishCreateRoute
  KnowledgesEnglishVocabulariesRoute: typeof KnowledgesEnglishVocabulariesRoute
  KnowledgesProgrammingCreateRoute: typeof KnowledgesProgrammingCreateRoute
  KnowledgesEnglishIndexRoute: typeof KnowledgesEnglishIndexRoute
  KnowledgesProgrammingIndexRoute: typeof KnowledgesProgrammingIndexRoute
  KnowledgesEnglishUnitEditRoute: typeof KnowledgesEnglishUnitEditRoute
  KnowledgesEnglishUnitIndexRoute: typeof KnowledgesEnglishUnitIndexRoute
  KnowledgesProgrammingUnitIndexRoute: typeof KnowledgesProgrammingUnitIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotesRoute: NotesRouteWithChildren,
  TravelsRoute: TravelsRouteWithChildren,
  AboutusIndexRoute: AboutusIndexRoute,
  ExpensesIndexRoute: ExpensesIndexRoute,
  FinancesIndexRoute: FinancesIndexRoute,
  KnowledgesIndexRoute: KnowledgesIndexRoute,
  TestIndexRoute: TestIndexRoute,
  KnowledgesEnglishCreateRoute: KnowledgesEnglishCreateRoute,
  KnowledgesEnglishVocabulariesRoute: KnowledgesEnglishVocabulariesRoute,
  KnowledgesProgrammingCreateRoute: KnowledgesProgrammingCreateRoute,
  KnowledgesEnglishIndexRoute: KnowledgesEnglishIndexRoute,
  KnowledgesProgrammingIndexRoute: KnowledgesProgrammingIndexRoute,
  KnowledgesEnglishUnitEditRoute: KnowledgesEnglishUnitEditRoute,
  KnowledgesEnglishUnitIndexRoute: KnowledgesEnglishUnitIndexRoute,
  KnowledgesProgrammingUnitIndexRoute: KnowledgesProgrammingUnitIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/notes",
        "/travels",
        "/about_us/",
        "/expenses/",
        "/finances/",
        "/knowledges/",
        "/test/",
        "/knowledges/english/create",
        "/knowledges/english/vocabularies",
        "/knowledges/programming/create",
        "/knowledges/english/",
        "/knowledges/programming/",
        "/knowledges/english/$unit/edit",
        "/knowledges/english/$unit/",
        "/knowledges/programming/$unit/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/notes": {
      "filePath": "notes/_pathlessLayout",
      "children": [
        "/notes/_pathlessLayout",
        "/notes/"
      ]
    },
    "/notes/_pathlessLayout": {
      "filePath": "notes/_pathlessLayout/route.tsx",
      "parent": "/notes",
      "children": [
        "/notes/_pathlessLayout/books/$id",
        "/notes/_pathlessLayout/books/create",
        "/notes/_pathlessLayout/books/"
      ]
    },
    "/travels": {
      "filePath": "travels/_pathlessLayout",
      "children": [
        "/travels/_pathlessLayout",
        "/travels/"
      ]
    },
    "/travels/_pathlessLayout": {
      "filePath": "travels/_pathlessLayout/route.tsx",
      "parent": "/travels",
      "children": [
        "/travels/_pathlessLayout/foods/test",
        "/travels/_pathlessLayout/coffees/",
        "/travels/_pathlessLayout/foods/"
      ]
    },
    "/about_us/": {
      "filePath": "about_us/index.tsx"
    },
    "/expenses/": {
      "filePath": "expenses/index.tsx"
    },
    "/finances/": {
      "filePath": "finances/index.tsx"
    },
    "/knowledges/": {
      "filePath": "knowledges/index.tsx"
    },
    "/notes/": {
      "filePath": "notes/index.tsx",
      "parent": "/notes"
    },
    "/test/": {
      "filePath": "test/index.tsx"
    },
    "/travels/": {
      "filePath": "travels/index.tsx",
      "parent": "/travels"
    },
    "/knowledges/english/create": {
      "filePath": "knowledges/english/create.tsx"
    },
    "/knowledges/english/vocabularies": {
      "filePath": "knowledges/english/vocabularies.tsx"
    },
    "/knowledges/programming/create": {
      "filePath": "knowledges/programming/create.tsx"
    },
    "/knowledges/english/": {
      "filePath": "knowledges/english/index.tsx"
    },
    "/knowledges/programming/": {
      "filePath": "knowledges/programming/index.tsx"
    },
    "/knowledges/english/$unit/edit": {
      "filePath": "knowledges/english/$unit/edit.tsx"
    },
    "/notes/_pathlessLayout/books/$id": {
      "filePath": "notes/_pathlessLayout/books/$id.tsx",
      "parent": "/notes/_pathlessLayout"
    },
    "/notes/_pathlessLayout/books/create": {
      "filePath": "notes/_pathlessLayout/books/create.tsx",
      "parent": "/notes/_pathlessLayout"
    },
    "/travels/_pathlessLayout/foods/test": {
      "filePath": "travels/_pathlessLayout/foods/test.tsx",
      "parent": "/travels/_pathlessLayout"
    },
    "/knowledges/english/$unit/": {
      "filePath": "knowledges/english/$unit/index.tsx"
    },
    "/knowledges/programming/$unit/": {
      "filePath": "knowledges/programming/$unit/index.tsx"
    },
    "/notes/_pathlessLayout/books/": {
      "filePath": "notes/_pathlessLayout/books/index.tsx",
      "parent": "/notes/_pathlessLayout"
    },
    "/travels/_pathlessLayout/coffees/": {
      "filePath": "travels/_pathlessLayout/coffees/index.tsx",
      "parent": "/travels/_pathlessLayout"
    },
    "/travels/_pathlessLayout/foods/": {
      "filePath": "travels/_pathlessLayout/foods/index.tsx",
      "parent": "/travels/_pathlessLayout"
    }
  }
}
ROUTE_MANIFEST_END */
